### PR TITLE
pass scan ref id with documentData

### PR DESCRIPTION
**Pull request by jnrepo**
passes scan reference id with documentData when netverify is successful

### CODE REVIEW

**Comment by kolphi** [comment]
Dear jnRepo,
thanks for reaching out to us with your change proposal. As Github is primarily the provider for offering our SDK and documentation in release state, we will not be able to accept your pull request within Github. Code changes are solely being done in our internal repositories.

Your proposal will be integrated in the upcoming release version 2.10 of our plugin.

best regards,
Jumio Mobile Team

**Comment by JumioMobileTeam** [comment]
Dear Sebastian,
thanks for reaching out to us with your change proposal. As Github is primarily the provider for offering our SDK and documentation in release state, we will not be able to accept your pull request within Github. Code changes are solely being done in our internal repositories.

We will integrate your change in the upcoming release version 2.10 of the plugin.

best regards,
Jumio Mobile Team

**Comment by jnrepo** [comment]
@JumioMobileTeam do ya'll know when 2.10 will be released?

**Comment by JumioMobileTeam** [comment]
Dear jnrepo,
Jumio Mobile SDK version 2.10.0 was released yesterday including a fix for your issue.

best regards,
Jumio Mobile Team

**Pull request closed without merging**
